### ISSUE TITLE
after lmh core cpssh lmh asks for passphrases of keys every time

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh_docker#10]
this is extremely annoying, can that be changed? Otherwise `lmh update` is quite useless.

**Comment by tkw1536** [comment]
From what I see there are 2 ways around this:

1) store a decrypted ssh key (without password) in the docker container
2) cache the password so that it only has to be entered once / session

**Comment by kohlhase** [comment]
It seems that git caches the password on its own in my local setlup, why does not not do that in docker?

**Comment by kohlhase** [comment]
I am just wondering why it behaves differently in docker and in MacOS.

**Comment by tkw1536** [comment]
because it's technically not git itself caching the password but the Mac OS
keychain. Inside docker, that does not exist.

**Comment by kohlhase** [comment]
so I guess I need https://help.github.com/articles/caching-your-github-password-in-git/#platform-linux
right?

**Comment by kohlhase** [comment]
hmmm, but that does not seem to work for me.

**Comment by tkw1536** [comment]
I'll have to set up ssh-agent, see
https://help.github.com/articles/working-with-ssh-key-passphrases/

**Comment by kohlhase** [comment]
OK, that seems like a good idea.

**Comment by tkw1536** [comment]
fixed by now.
