### ISSUE TITLE
graphics library installation error

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh_docker#20]
I am not sure that this is the right place to report this error, ...
running `lmh omdoc` on `MiKoMH/GenCS/source/graphs-trees/en/bbt-size.tex`
and get the following error

```
(post-processing...
(Scan balanced-binary-trees.omdoc processing... 0.01 sec)
(CrossRef balanced-binary-trees.omdoc processing... 0.00 sec)
(Graphics balanced-binary-trees.omdoc 2 to process...
Error:imageprocessing:imageclass No image processing module found for complex transformations
    No image processing module found for complex transformations
    Simplifying transformation of /Users/kohlhase/localmh/MathHub/MiKoMH/GenCS/source/graphs-trees/PIC/bbt-large.png.
    Please install one of: Graphics::Magick,Image::Magick
    In Post::Graphics[@0xcd81ef8] ->transformGraphic
 0.10 sec)
(XMath[w/OpenMath+MathML::Presentation] balanced-binary-trees.omdoc 10 to process... 0.01 sec)
(Xslt[using /path/to/localmh/ext/sTeX/sty/../xsl/omdocpost.xsl] balanced-binary-trees.omdoc processing... 0.00 sec)
```

this seems to be a docker installation error to me.

**Comment by kohlhase** [comment]
maybe @cmaeder or @m-iancu have some ideas about this.

**Comment by tkw1536** [comment]
I have a fix. This can be run to fix it in-place

``` bash
lmh docker sshell # open a shell in docker, make sure it is running
apt-get update && apt-get -y install perlmagick # install the perlmagick package
exit
```

I am compiling and updating the docker image right now.

**Comment by tkw1536** [comment]
@m-iancu You probably want to use this fix inside MathHub as well

**Comment by kohlhase** [comment]
@m-iancu I think that this will fix quite a lot of the remaining LaTeXML errors in MathHub. This is good news.

**Comment by m-iancu** [comment]
perlmagick was already installed on MathHub but there may still be other missing packages. It's good we have the dockerfile for localmh to maintain/document what is needed.
