### ISSUE TITLE
more documentation on using lmh 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh_docker#3]
The documentation stops short really, since it only discusses how to install, even "using lmh" does not say anything about 
- I guess that docker shell has to be running. 
- how can I start docker in my startup in Mac OS?
- how do I invoke lmh (I guess just as normal) does this only work from the docker shell? 
- does lmh have to be on my path? What does that  even mean? 
  After all this is end-user documentation

Also it would be good to have "install docker" also cover Mac OS and windows.

**Comment by kohlhase** [comment]
Oh, and I would also like to know, will I have to update this script? ever? If so how, ...

**Comment by kohlhase** [comment]
Oh, and docker setup tells me 

```

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH=/Users/kohlhase/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1

```

does that mean anyting for me (or other `lmh` users)

**Comment by tkw1536** [comment]
@kohlhase I have updated the script (quite a lot). You should probably re-install following the new instructions in the README.

**Comment by kohlhase** [comment]
I did that, and I am getting much farther. 

```
lmhwrap start
Creating new container for lmh ...
Unable to find image 'tkw01536/localmh:latest' locally
Pulling repository tkw01536/localmh
dbc92befea97: Pulling image (latest) from tkw01536/localmh
dbc92befea97: Pulling image (latest) from tkw01536/localmh, endpoint: https://registry-1.docker.io/v1/
dbc92befea97: Pulling dependent layers
511136ea3c5a: Pulling metadata
511136ea3c5a: Pulling fs layer
511136ea3c5a: Download complete
cba45d5f1898: Pulling metadata
cba45d5f1898: Pulling fs layer
cba45d5f1898: Download complete
928892d9c89c: Pulling metadata
928892d9c89c: Pulling fs layer
928892d9c89c: Download complete
629c865dd7bd: Pulling metadata
629c865dd7bd: Pulling fs layer
629c865dd7bd: Download complete
71a59cbb7f0e: Pulling metadata
71a59cbb7f0e: Pulling fs layer
```

But it takes quite a wile, so I am wondering what is happening. Will there be a success message in the docker shell? Maybe the documentation should mention that things take long to set up and what to expect here.

**Comment by kohlhase** [comment]
also I would put the caveats section after the "using lmh" section, as it only pertains to people who want to develop lmh (maybe the section heading should reflect this).

**Comment by tkw1536** [comment]
It has to pull about 1.5 GB of data that is normal (it will take a while). Please read the README, I have updated the script and to get a shell the command is now: 

```
lmh[wrap] core start
```

From the README: 

> If the wrapper script is named "lmh" you can use the normal lmh commands seemlessly. The only exception from this is "lmh core" which is handled by the wrapper script only.
