### ISSUE TITLE
tex live version? 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh_docker#8]
How do I find out the texlive version of docker? I am missing tikzlibrarytikzmark.code.tex, wich is in recent texlive, but not on the docker I have.

**Comment by tkw1536** [comment]
I believe it's texlive 2012. You can open a shell inside docker and check
from there.

**Comment by kohlhase** [comment]
yes, it is 2012. how can I upgrade to 2014? It would be good, if we had 2014 for the default case.

**Comment by tkw1536** [comment]
Upgrading isn't simple. To upgrade, I will probably have to make a new docker image with a vanilla 2014 installation in it.

**Comment by tkw1536** [comment]
I will probably add something similar to https://github.com/leodido/dockerfiles/tree/master/texlive:2014 in the dockerfile.

**Comment by kohlhase** [comment]
sounds good, what do I have to to participate? Can I just update? Do I have to pull a new one?

**Comment by tkw1536** [comment]
Once finished you will have to re-pull the docker image. (I will close this issue once I have finished it). 

To update:

``` bash
# make sure the docker daemon (boot2docker) is running
# then pull the new image from the server, this will take a while
docker pull KWARC/localmh

# remove the old container
# this keeps all your data intact. 
lmh core destroy

# Set up the new container
lmh core put $HOME/.gitconfig /root/.gitconfig
lmh core cpssh

# Re-compile all the dependencies 
lmh setup --reinstall all

# that's it. 
```

**Comment by tkw1536** [comment]
I have done some testing and texlive 2014 installation went rather smoothly. The only problem is that the image size is now around 4.8 GB. I will try to compress it a bit and then push it to dockerhub.

**Comment by tkw1536** [comment]
@kohlhase Pushed, you can upgarde now.

**Comment by kohlhase** [comment]
could you remind me how to do that? I do not think that this is in the documentation.

**Comment by tkw1536** [comment]
See the comment above
https://github.com/KWARC/localmh_docker/issues/8#issuecomment-74379257

**Comment by kohlhase** [comment]
sorry, did not see. I will wait for the texmf.cnf update.

**Comment by kohlhase** [comment]
the instruction above does not see to work 

```
Michael-Kohlhases-MacBook-Pro:assignments kohlhase$ docker pull KWARC/localmh
FATA[0000] Invalid namespace name (KWARC), only [a-z0-9_] are allowed, size between 4 and 30 
```

**Comment by tkw1536** [comment]
Fixed offline.
